version: '3.9'
services:
  tutoring:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tutoring-main
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./web:/app/web
    command: bash -c "python /app/web/manage.py migrate --noinput && python /app/web/manage.py runserver 0.0.0.0:8000"
    networks:
      - tutoring

  coverapi:
    image: php:7.4-cli
    container_name: tutoring-coverapi
    volumes:
      - ./coverapi:/app
    ports:
      - 8001:8001
    command: bash -c "cd /app && php -S 0.0.0.0:8001/"
    networks:
      - tutoring

networks:
  tutoring:
