# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 14:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CoverAccounts', '0006_auto_20170130_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=True)),
                ('is_listed', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('offered_languages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_anonymous', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoverAccounts.CoverMember')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.Subject'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offered_subjects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.Subject'),
        ),
        migrations.AddField(
            model_name='offer',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='CoverAccounts.CoverMember'),
        ),
    ]
