# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='offered_languages',
        ),
        migrations.AddField(
            model_name='offer',
            name='offered_languages',
            field=models.ManyToManyField(to='tutors.Language'),
        ),
        migrations.RemoveField(
            model_name='offer',
            name='offered_subjects',
        ),
        migrations.AddField(
            model_name='offer',
            name='offered_subjects',
            field=models.ManyToManyField(to='tutors.Subject'),
        ),
    ]
