# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_auto_20170130_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(default='Im searching for a little extra help with my course imperative programming. I have never programmed before this course and it is more difficult than i expected. I hope that someone can help me with my course so i can pass it, because i like the programming it self but its hard. i like to hear from you soon.'),
            preserve_default=False,
        ),
    ]
