# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0004_request_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name']},
        ),
    ]
