# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0005_auto_20170202_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='is_anonymous',
        ),
        migrations.RemoveField(
            model_name='request',
            name='is_anonymous',
        ),
    ]
