# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoverAccounts', '0002_covermember_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='covermember',
            name='has_module_perms',
            field=models.BooleanField(default=False),
        ),
    ]
