# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 13:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoverAccounts', '0003_covermember_has_module_perms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='covermember',
            name='has_module_perms',
        ),
    ]
