# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoverAccounts', '0004_remove_covermember_has_module_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='covermember',
            name='cover_id',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
