# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoverAccounts', '0005_covermember_cover_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covermember',
            old_name='joined',
            new_name='first_login',
        ),
        migrations.AddField(
            model_name='covermember',
            name='first_name',
            field=models.CharField(default='raf', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='covermember',
            name='last_name',
            field=models.CharField(default='bank', max_length=255),
            preserve_default=False,
        ),
    ]
