# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CoverAccounts', '0006_auto_20170130_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CoverAccounts.Conversation')),
            ],
        ),
        migrations.AddField(
            model_name='covermember',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
