# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CoverAccounts', '0007_auto_20170215_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='conversation',
        ),
    ]
