# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoverAccounts', '0012_covermember_appears_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='covermember',
            name='receives_mail_notification',
            field=models.BooleanField(default=True),
        ),
    ]
