# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-14 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoverAccounts', '0016_auto_20170508_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='covermember',
            name='is_alpha_user',
            field=models.BooleanField(default=True),
        ),
    ]
