# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-28 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CoverAccounts', '0023_auto_20180128_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covermember',
            name='telegram_bot_token',
            field=models.CharField(default=None, help_text='You can setup the "CACTuS Messenger" bot in Telegram. The bot will ask you for this code.', max_length=160, unique=True, verbose_name='Telegram Bot Token'),
        ),
    ]
