# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 16:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messages', '0003_auto_20170308_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={},
        ),
    ]
